# In your project repo: .github/workflows/ci.yml
name: Organization CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: "0 9 * * 1" # Weekly dependency updates at 9 AM on Monday

jobs:
  # Ruff runs only if Python files changed (logic is inside the reusable workflow)
  ruff-format:
    uses: Homies-Tech-Innovation/.github/.github/workflows/ruff-format.yml@main
    permissions:
      contents: write # To commit formatting changes
      pull-requests: write # To comment on the PR
    secrets: inherit

  # This job will run on PRs to the main branch that are NOT from the dev branch.
  pr-guard:
    if: github.event_name == 'pull_request' && github.base_ref == 'main' && github.head_ref != 'dev'
    uses: Homies-Tech-Innovation/.github/.github/workflows/pr-guard.yml@main
    permissions:
      pull-requests: write # To comment and add labels
    secrets: inherit
